# Capítulo 4 - numpy


---


### Exercícios Propostos 1


##### 1. Crie um _array_ de tamanho 21 com valores linearmente espaçados entre 0 e 51.


In [1]:
# Importar numpy
import numpy as np


In [2]:
# Criar array de tamanho 21 com valores linearmente espaçados entre 0 e 1
array = np.linspace(0, 1, 21)
print(array)


[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.  ]


##### 2. Crie 2 _arrays_: um de números pares de 0 até 51 e outro também de números pares de 100 até 50. Em seguida, os concatene e mostre os resultados ordenados.


In [3]:
# Criar 2 arrays, um de números pares de 0 a 51 e outro de números pares de 100 a 50
array_1 = np.arange(0, 51, 2)
array_2 = np.arange(100, 50, -2)
print(array_1)
print(array_2)


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52]


In [4]:
# Concatenar os arrays e mostrar os resultados ordenados
array_resultante = np.concatenate((array_1, array_2))
print(array_resultante)


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50 100  98  96  94  92  90  88  86  84  82
  80  78  76  74  72  70  68  66  64  62  60  58  56  54  52]


##### 3. Ordene os resultados do array resultante da questão 2 em ordem decrescente.


In [5]:
# Ordenar o array resultante em ordem decrescente
array_ordenado = np.sort(array_resultante)[::-1]
print(array_ordenado)


[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2   0]


##### 4. Crie uma matriz formada somente por uns de tamanho 3x4. Em seguida, transforme-a em um _array_ unidimensional.


In [6]:
# Criar matriz de 1 de tamanho 3x4
matriz = np.ones((3, 4))
print(matriz)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# Transformar a matriz em um array unidimensional
array_1d = matriz.flatten()
print(array_1d)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


##### 5. Crie uma matriz de tamanho qualquer. Extraia seu número de linhas e colunas, multiplique-os, e diga se esta matriz poderia se tornar um vetor com número par ou ímpar de elementos.


In [8]:
# Criar matriz de tamanho qualquer
nova_matriz = np.random.rand(np.random.randint(1, 10),
                             np.random.randint(1, 10))
print(nova_matriz)


[[0.86676418 0.00837937 0.833455   0.56475357 0.39657698 0.35328053
  0.40554189 0.00836639]]


In [9]:
# Extrair os números de linhas e de colunas da matriz e multiplicá-los
num_linhas = nova_matriz.shape[0]
num_colunas = nova_matriz.shape[1]
print("Número de Linhas =", num_linhas)
print("Número de Colunas =", num_colunas)
print("Linhas * Colunas =", num_linhas * num_colunas)


Número de Linhas = 1
Número de Colunas = 8
Linhas * Colunas = 8


In [10]:
# Dizer se a matriz poderia se tornar um vetor com número par ou ímpar de elementos
tamanho = nova_matriz.size
print(f"A matriz possui tamanho {tamanho}...")
if tamanho % 2 == 0:
    print("Então, ela pode se tornar um vetor com número par de elementos!")
else:
    print("Então, ela pode se tornar um vetor com número ímpar de elementos!")


A matriz possui tamanho 8...
Então, ela pode se tornar um vetor com número par de elementos!


---


### Exercícios Propostos 2


##### 1. Crie um _array_ de `float` com 10 elementos positivos e negativos entre 0 e 1. Em seguida, multiplique seus valores por 100 e crie um novo vetor apenas com a parte inteira destes números. Use `seed(5)` antes.


In [11]:
# seed(5)
np.random.seed(5)


In [12]:
# Array de float com 10 elementos entre 0 e 1, positivos e negativos (entre -1 e 1)
array_float = np.random.uniform(-1, 1, 10)
print(array_float)


[-0.55601366  0.74146461 -0.58656169  0.83722182 -0.02317762  0.22348773
  0.53181571  0.03683598 -0.406399   -0.62455754]


In [13]:
# Array multiplicado por 100
array_float_x100 = array_float * 100
print(array_float_x100)


[-55.60136578  74.14646124 -58.65616893  83.72218159  -2.31776224
  22.34877258  53.1815713    3.68359757 -40.63989968 -62.45575427]


In [14]:
# Novo array apenas com a parte inteira
array_int = (array_float_x100).astype(int)
print(array_int)

[-55  74 -58  83  -2  22  53   3 -40 -62]


##### 2. Crie uma matriz de tamanho 4x4 formada por números aleatórios inteiros entre 1 e 50. Use `seed(10)` antes.


In [15]:
# seed(10)
np.random.seed(10)


In [16]:
# Matriz 4x4 com inteiros entre 1 e 50
matriz_int = np.random.randint(1, 50, (4, 4))
print(matriz_int)

[[10 37 16  1]
 [29 26 30 49]
 [30  9 10  1]
 [43 41 37 17]]


##### 3. Mostre o resultado da média de cada linha e cada coluna da matriz gerada pela questão 2 e, em seguida, apresente o maior valor das médias para as linhas e também para as colunas.


In [17]:
# Média de cada linha e de cada coluna e a maior média de cada
media_linhas = matriz_int.mean(axis=1)
media_colunas = matriz_int.mean(axis=0)
print("Média das Linhas =", media_linhas)
print("Média das Colunas =", media_colunas)
print("Maior Média das Linhas =", media_linhas.max())
print("Maior Média das Colunas =", media_colunas.max())


Média das Linhas = [16.  33.5 12.5 34.5]
Média das Colunas = [28.   28.25 23.25 17.  ]
Maior Média das Linhas = 34.5
Maior Média das Colunas = 28.25


##### 4. Baseado na matriz gerada na questão 2, mostre a quantidade de aparições de cada um dos números na mesma. EM seguida, mostre apenas os números que aparecem 2 vezes.


In [18]:
# Quantidade de aparições de cada número na 'matriz_int'
aparicoes, quantidade = np.unique(matriz_int, return_counts=True)
print((aparicoes, quantidade))


(array([ 1,  9, 10, 16, 17, 26, 29, 30, 37, 41, 43, 49]), array([2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1], dtype=int64))


In [19]:
# Números que aparecem duas vezes
print(aparicoes[quantidade == 2])


[ 1 10 30 37]


---


### Exercícios Propostos 3


##### 1. Apresente a porcentagem das missões que deram certo.


In [20]:
# Importar dataset
dataset = np.loadtxt('data/space.csv', delimiter=';',
                     dtype=str, encoding='utf-8', skiprows=1)


In [21]:
# Definir as colunas
all_companies = dataset[:, 1]
all_locations = dataset[:, 2]
all_costs = dataset[:, 6].astype(float)
all_statuses = dataset[:, 7]


In [22]:
# Porcentagem das missões que deram certo
successes = len(all_statuses[all_statuses == 'Success'])
percentage = successes / len(all_statuses) * 100
print(percentage)


89.70860314523588


##### 2. Qual a média de gastos de uma missão espacial se baseando em missões que possuam `valores disponíveis > 0`?


In [23]:
# Média de gastos de missões, onde o gasto > 0
positive_cost = all_costs[all_costs > 0]
average_cost = np.mean(positive_cost)
print(average_cost)

153.7921991701245


##### 3. Encontre quantas missões espaciais neste _dataset_ foram realizadas pelos EUA.


In [24]:
# Quantidade de missões feitas pelos USA
usa_missions = all_locations[np.char.find(all_locations, 'USA') != -1]
print(len(usa_missions))


1344


##### 4. Encontre qual foi a missão mais cara realizada pela empresa "SpaceX".


In [25]:
# Maior gasto (missão mais cara) da SpaceX
spacex_missions = dataset[np.char.find(all_companies, 'SpaceX') != -1]
spacex_expenses = spacex_missions[:, 6].astype(float)
most_expensive = spacex_missions[np.argmax(spacex_expenses)]
print(most_expensive[6].astype(float))


90.0


##### 5. Mostre o nome das empresas que já realizaram missões espaciais juntamente com suas respectivas quantidades de missões. Use o `for` no final para mostrar as informações.


In [26]:
# Configura
company_names, num_missions = np.unique(all_companies, return_counts=True)
for company_name, missions in zip(company_names, num_missions):
    print(company_name, missions)


AEB 3
AMBA 8
ASI 9
Arianespace 279
Arm??e de l'Air 4
Blue Origin 12
Boeing 136
CASC 251
CASIC 5
CECLES 4
CNES 8
Douglas 1
EER 1
ESA 13
Eurockot 13
ExPace 10
Exos 4
General Dynamics 251
IAI 11
ILS 46
IRGC 1
ISA 13
ISAS 30
ISRO 76
JAXA 7
KARI 3
KCST 5
Khrunichev 1
Kosmotras 22
Land Launch 7
Landspace 1
Lockheed 79
MHI 84
MITT 7
Martin Marietta 114
NASA 203
Northrop 83
OKB-586 2
OneSpace 1
RAE 2
RVSN USSR 1777
Rocket Lab 13
Roscosmos 55
SRC 3
Sandia 1
Sea Launch 36
SpaceX 100
Starsem 1
ULA 140
US Air Force 161
US Navy 17
UT 5
VKS RF 201
Virgin Orbit 1
Yuzhmash 2
i-Space 1
